# Generated by Django 3.1.5 on 2021-01-27 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lafayette', '0002_amigo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre del Cliente')),
                ('telefono', models.CharField(max_length=10, verbose_name='Número de teléfono')),
                ('opcion', models.CharField(choices=[('Vender', 'Vender'), ('Rentar', 'Rentar')], max_length=20, verbose_name='Vender o Rentar')),
                ('datos', models.CharField(max_length=300, verbose_name='Datos de la propiedad')),
            ],
        ),
        migrations.AlterField(
            model_name='amigo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
