# Generated by Django 3.1.5 on 2021-01-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lafayette', '0006_amigo_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amigo',
            name='img',
            field=models.ImageField(upload_to='static/media', verbose_name='Seleccionar una imagen'),
        ),
        migrations.AlterField(
            model_name='amigo',
            name='publicar',
            field=models.CharField(choices=[('1', 'Publica'), ('2', 'Privada')], max_length=20, verbose_name='Esta nota sera ?'),
        ),
    ]
