# Generated by Django 3.1.5 on 2021-02-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lafayette', '0010_auto_20210202_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Correo Electronico'),
            preserve_default=False,
        ),
    ]
