# Generated by Django 3.1.5 on 2021-02-05 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lafayette', '0011_contacto_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amigo',
            name='estado',
            field=models.CharField(max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='amigo',
            name='municipio',
            field=models.CharField(max_length=30, verbose_name='Municipio'),
        ),
    ]
