# Generated by Django 3.1.5 on 2021-02-10 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lafayette', '0012_auto_20210205_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='calle',
            field=models.CharField(default=' ', max_length=100, verbose_name='Calle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacto',
            name='colonia',
            field=models.CharField(default=' ', max_length=30, verbose_name='Colonia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacto',
            name='cp',
            field=models.CharField(default=' ', max_length=5, verbose_name='Código postal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacto',
            name='estado',
            field=models.CharField(default=' ', max_length=30, verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacto',
            name='municipio',
            field=models.CharField(default=' ', max_length=30, verbose_name='Municipio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacto',
            name='tipo',
            field=models.CharField(default=' ', max_length=30, verbose_name='Tipo de inmueble'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacto',
            name='ubicacion',
            field=models.CharField(default=' ', max_length=50, verbose_name='Ubicación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amigo',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/media', verbose_name='Seleccionar una imagen'),
        ),
        migrations.CreateModel(
            name='Prospecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre del Prospecto')),
                ('telefono', models.CharField(max_length=10, verbose_name='Número de teléfono')),
                ('fechac', models.DateField(verbose_name='Fecha de contacto')),
                ('fechap', models.DateField(verbose_name='Fecha de plática')),
                ('fechai', models.DateField(verbose_name='Fecha de Inscripción')),
                ('interesado', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=20, verbose_name='Interesado')),
                ('inscrito', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=20, verbose_name='Inscrito')),
                ('contactado', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=20, verbose_name='Contactado')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
