# Generated by Django 3.1.5 on 2021-03-15 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lafayette', '0013_auto_20210209_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospecto',
            name='fechai',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inscripción'),
        ),
    ]
