# Generated by Django 3.1.5 on 2021-03-15 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lafayette', '0016_auto_20210314_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='ubicacion',
        ),
    ]
