# Generated by Django 3.1.5 on 2021-01-26 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20, verbose_name='Operación a realizar')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=50, verbose_name='Producto a ofertar')),
            ],
        ),
        migrations.CreateModel(
            name='Amigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=60, verbose_name='Nombre del Cliente')),
                ('municipio', models.CharField(max_length=50, verbose_name='Municipio')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=10, verbose_name='Telefono')),
                ('opcion', models.CharField(choices=[('Ofrece', 'Ofrece'), ('Desea', 'Desea')], max_length=20, verbose_name='Operacion a realizar')),
                ('nota', models.CharField(max_length=300, verbose_name='Notas')),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lafayette.operacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lafayette.producto')),
            ],
        ),
    ]
