# Generated by Django 3.1.5 on 2021-01-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lafayette', '0004_auto_20210127_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='amigo',
            name='titulo',
            field=models.CharField(default=' ', max_length=300, verbose_name='Título'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amigo',
            name='nota',
            field=models.CharField(max_length=300, verbose_name='Descripción del inmueble'),
        ),
        migrations.AlterField(
            model_name='amigo',
            name='opcion',
            field=models.CharField(choices=[('Ofrece', 'Ofrece'), ('Desea', 'Desea')], max_length=20, verbose_name='Operacion a realizar'),
        ),
    ]
