# Generated by Django 3.1.5 on 2021-01-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lafayette', '0005_auto_20210127_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='amigo',
            name='img',
            field=models.ImageField(default=' ', upload_to='static/media'),
            preserve_default=False,
        ),
    ]
