# Generated by Django 3.1.5 on 2021-01-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210128_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ventas',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
